## Numpy
learn about with me

In [1]:
import numpy as np

## creating array for list

In [2]:
arr_1d = np.array([1,2,3,4,5])
print("1d array",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2d array",arr_2d)

1d array [1 2 3 4 5]
2d array [[1 2 3]
 [4 5 6]]


## list vs numpy array

In [7]:
py_list = [1,2,3]
print("python list multiplicattion",py_list*2)

np_array = np. array([1,2,3])
print("python array multiplication",np_array *2)



import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n list operstion time",time.time()-start)

start = time.time()
np_array = np.arange(1000000)*2
print("\n list operstion time",time.time()-start)


python list multiplicattion [1, 2, 3, 1, 2, 3]
python array multiplication [2 4 6]

 list operstion time 0.060623884201049805

 list operstion time 0.00532984733581543


## creating array from scratch

In [11]:
zeros = np.zeros((3,4))
print("zeros array\n",zeros)

ones = np.ones((2,3))
print("ones array\n",ones)

full = np.full((2,2),7)
print("full array\n",full)

random = np.random.random((2,3))
print("random array\n",random)

sequence = np.arange(0, 10, 2)
print("sequence array\n",sequence)





zeros array
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array
 [[1. 1. 1.]
 [1. 1. 1.]]
full array
 [[7 7]
 [7 7]]
random array
 [[0.45644182 0.66573172 0.6311052 ]
 [0.64577873 0.47815873 0.96713499]]
sequence array
 [0 2 4 6 8]


### vector, matrix and tensor

In [14]:
vector = np.array([1,2,3])
print("vector",vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("matrix",matrix)

tensor = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print("tensor",tensor)


vector [1 2 3]
matrix [[1 2 3]
 [4 5 6]]
tensor [[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


### Array properties

In [15]:
arr = np.array([[1,2,3],[4,5,6]])
print("shape",arr.shape)
print("Dimension",arr.ndim)
print("size",arr.size)
print("DType",arr.dtype)

shape (2, 3)
Dimension 2
size 6
DType int64


### Array Reshaping

In [14]:
import numpy as np

arr = np.arange(12)
print("original array",arr)

reshape = arr.reshape((3,4))
print("reshape array",reshape)

flattened = reshape.flatten()
print("flattened array",flattened)

# ravel (returns view, instead of copy)
raveled = reshape.ravel()
print("ravel array",raveled)

#transpose
transpose = reshape.T
print("transpose array", transpose)

original array [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshape array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11]
ravel array [ 0  1  2  3  4  5  6  7  8  9 10 11]
transpose array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
