## Numpy Array operation


In [2]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("slicing",arr[2:7])
print("with step",arr[1:8:2])
print("negative indexing",arr[-3])


slicing [3 4 5 6 7]
with step [2 4 6 8]
negative indexing 8


In [ ]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("specific element",arr_2d[1,2])
print("entire row",arr_2d[1])
print("entire column",arr_2d[:,1])

specific element 6
entire row [4 5 6]
entire coloumn [2 5 8]


# Sorting

In [ ]:
unsorted = np.array([3,2,1,5,4,7,6,8,9])
print("sorted array",np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("sorted 2d array",np.sort(arr_2d_unsorted, axis=0))



sorted array [1 2 3 4 5 6 7 8 9]
sorted 2d array [[1 1]
 [2 2]
 [3 3]]


## Filter

In [10]:
## filter

numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2==0]
print("even numbers",even_number)


even numbers [ 2  4  6  8 10]


## Filter with mask

In [11]:
mask = numbers > 5
print("numbers greater than 5",numbers[mask])

numbers greater than 5 [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [12]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("np where", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
np where [ 6  7  8  9 10]


In [13]:
condition_array = np.where(numbers > 5)
print(condition_array)

(array([5, 6, 7, 8, 9]),)


## Adding and removind data

In [17]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
combined_arr = np.concatenate((arr1, arr2))
print(combined_arr)

[1 2 3 4 5 6]


## Array compatibility

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
print("compatibility shapes",a.shape == b.shape)

compatibility shapes False


In [22]:
original = np.array([[1,2],[3,4]])
new_row= np.array([5,6])

with_new_row = np.vstack((original,new_row))
print(original)
print(with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))
print("with new col ",with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
with new col  [[1 2 7]
 [3 4 8]]


In [ ]:
arr = np.array([1,2,3,4,5,])
deleted = np.delete(arr ,1)
print("array after deletion",deleted)

arr after deletion [1 3 4 5]
